spring.application.name=banque-mongo
spring.data.mongodb.uri=mongodb+srv://iassine_db_user:73Dxypm5auUtOzI4@cluster0.ia9chtd.mongodb.net/banque_tp?retryWrites=true&w=majority
spring.data.mongodb.database=banque_tp